const words_2022 = [
  "instance", 
  "instant",
  "direct",
  "direction",
  "ideally",
  "Manipulation",
  "manual",
  "observe",
  "obey",
  "stale",
  "assistant",
  "bread",
  "January",
  "February",
  "March",
  "April",
  "May",
  "Jun",
  "July",
  "august",
  "September",
  "October",
  "November",
  "December",
  "kick off",
  "invalidate",
  "deliberately",
  "reserve",
  "reserved",
  "arena",
  "strength",
  "notion",
  "discard",
  "spirit",
  "seek",
  "paradise",
  "lightly",
  "merely",
  "exits",
  "entrances",
  "sideline",
  "happen to",
  "industrious",
  "revert",
  "luxury",
  "otherwise",
  "budget",
  "restore", // vi. 修复 恢复 归还   restored 精力充沛
  "renew", // vi. 重新开始、复兴    renewed 更新的、复兴的、重建的
  "revive", // vi. 苏醒、复活  revived 重生的
  "reclaim", // vi. 开垦、回收、纠正、教化  reclaimed 回收的、再造的
  "redeem", // vi. 赎回、挽回、补偿   redeemed 救赎的
  "poise",
  "youth",
  "matter",
  "detect",
  "boldness",
  "bold",
  "opposite",
  "fatal",
  "prune",
  "perfume",
  "Personality",
  "predictable",
  "forecast",
  "strive",
  "constructive",
  "additional",
  "In addition to",
  "requirement",
  "ordinary",
  "extraordinary",
  "perseverance",
  "attain",
  "ecosystem",
  "addons",
  "essential",
  "fundamental",
  "internal",
  "compose",
  "compose out",
  "valuable",
  "advantage",
  "take advantage of",
  "integration",
  "reproduce",
  "abstraction",
  "pattern",
  "assume",
  "trade-off",
  "in terms of",
  "demonstrates",
  "as well as",
  "concise",
  "efficiently",
  "terminology",
  "standalone",
  "briefly",
  "subtract",
  "dive into",
  "principle",
  "Prerequisites",
  "In particular",
  "ahead of time",
  "recommend",
  "primary",
  "come up with",
  "convention",
  "potential",
  "typical",
  "nerd",
  "will",
  "reliability",
  "courage",
  "abandon",
  "tidy",
  "clear up",
  "take part in"
];

const sentences_2022 = [
  "It is hard to wake up someone who is pretending to be asleep.",
  "Victory is in having done your best. If you've done your best, you've won.",
  "A ship is safe in harbor,but that's not what ships are for.",
  "Shall we go for lunch now?",
  "Always believe in yourself. Do this and no matter where you are, you will have nothing to fear.",
  "A leader is a dealer in hope.",
  "The key is not the will to win. Everybody has that. It is the will to prepare to win, and that is important.",
  "The truth is, everyone is going to hurt you. You just got to find the ones worth suffering for",
  "The beauty of a woman is not in the clothes she wears, the figure that she carries or the way she combs her hair.",
  "Doubt is the key to knowledge.",
  "Books must be read as deliberately and reservedly as they are written.",
  "The sidelines are not where you want to live your life. The world needs you in the arena.",
  "What makes you different or weird, that's your strength.",
  "There is nothing I would not do for those who are really my friends. I have no notion of loving people by halves, it is not my nature.",
  "True love is like a fine wine, the older the better.",
  "If we seek paradise outside ourselves, we cannot have paradise in our hearts.",
  "Before you are a leader, success is all about growing yourself. When you become a leader, success is all about growing others.",
  "He who has great power should use it lightly.",
  "The most important thing a father can do for his children is to love their mother.",
  "All the world's a stage, and all the men and women merely players. They have their exits and their entrances; and one man in his time plays many parts.",
  "People, even more than things, have to be restored, renewed, revived, reclaimed, and redeemed; never throw out anyone.",
  "It is not enough to be industrious, so are the ants. What are you industrious for?",
  "A great man is always willing to be little.",
  "Luxury must be comfortable, otherwise it is not luxury.",
  "What would it be like to swing on a star, or walk on a cloud? Would it be anything like what I feel whenever you are near?",
  "For beautiful eyes, look for the good in others; for beautiful lips, speak only words of kindness; and for poise, walk with the knowledge that you are never alone.",
  "Life isn't about waiting for the storm to pass. It's about learning to dance in the rain.",
  "Youth is a quality, not a matter of circumstances.",
  "Whatever you can do, or dream you can, begin it. Boldness has genius, power and magic in it.",
  "The ones that love us never really leave us",
  "Death is not the opposite of life, but the part of it.",
  "Failure is not fatal, but failure to change might be.",
  "The empty vessels make the greatest sound.",
  "Natural abilities are like natural plants that need pruning by study.",
  "Personality is to man what perfume is to a flower.",
  "Education is what remains after one has forgotten everything he learned in school.",
  "With ordinary talent and extraordinary perseverance, all things are attainable.",
  "Activity is the only road to knowledge.",
  "Wise men speak because they have something to say; fools because they have to say something.",
  "Beauty is when you can appreciate yourself. When you love yourself, that's when you are most beautiful.",
  "We must accept finite disappointment, but we must never lose infinite hope.",
  "You can get help from teachers, but you are going to have to learn a lot by yourself, sitting alone in a room.",
  "Simplicity is prerequisite for reliability",
  "If the path be beautiful, let us not ask where it leads.",
  "Resolve to perform what you ought. Perform without fail what you resolve.",
  "The more we try to understand one another, the more exceptional each of us will be. But we have to try.",
  "The only person you are destined to become is the person you decide to be."
]

console.log(`${words_2022.length}/1000`);
