const words_2022 = [
  "instance", 
  "instant",
  "direct",
  "direction",
  "ideally",
  "Manipulation",
  "manual",
  "observe",
  "obey",
  "stale",
  "assistant",
  "bread",
  "January",
  "February",
  "March",
  "April",
  "May",
  "Jun",
  "July",
  "august",
  "September",
  "October",
  "November",
  "December",
  "kick off",
  "invalidate",
  "deliberately",
  "reserve",
  "reserved",
  "arena",
  "strength",
  "notion",
  "discard",
  "spirit",
  "seek",
  "paradise",
  "lightly"
];

const sentences_2022 = [
  "It is hard to wake up someone who is pretending to be asleep.",
  "Victory is in having done your best. If you've done your best, you've won.",
  "A ship is safe in harbor,but that's not what ships are for.",
  "Shall we go for lunch now?",
  "Always believe in yourself. Do this and no matter where you are, you will have nothing to fear.",
  "A leader is a dealer in hope.",
  "The key is not the will to win. Everybody has that. It is the will to prepare to win, and that is important.",
  "The truth is, everyone is going to hurt you. You just got to find the ones worth suffering for",
  "The beauty of a woman is not in the clothes she wears, the figure that she carries or the way she combs her hair.",
  "Doubt is the key to knowledge.",
  "Books must be read as deliberately and reservedly as they are written.",
  "The sidelines are not where you want to live your life. The world needs you in the arena.",
  "What makes you different or weird, that's your strength.",
  "There is nothing I would not do for those who are really my friends. I have no notion of loving people by halves, it is not my nature.",
  "True love is like a fine wine, the older the better.",
  "If we seek paradise outside ourselves, we cannot have paradise in our hearts.",
  "Before you are a leader, success is all about growing yourself. When you become a leader, success is all about growing others.",
  "He who has great power should use it lightly.",
  "The most important thing a father can do for his children is to love their mother."
]

console.log(`${words_2022.length}/1000`);
